syntax on
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
set wrap
set tabstop=4
set background=light
" Always show statusline
set laststatus=2
" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256
" Always show the command as it is being typed.
set showcmd